#!/bin/bash


#SBATCH --job-name="GATK: Variant_Calling using ploidy 10 (JointGenotyping)"
#SBATCH --chdir=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/Aisha/T2T_variant_calling/03_T2T_RNAseq_variant_calling/scripts
#SBATCH --output=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/Aisha/T2T_variant_calling/03_T2T_RNAseq_variant_calling/scripts/cons_uniq_morphs.T2T_masked_small_blast_hits/GATK/out/02.02.GATK.pldy_10.JointGenotyping.MQ30.BQ15.MAA20.GC75000.SC10.bqsr.%A_%a.out
#SBATCH --error=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/Aisha/T2T_variant_calling/03_T2T_RNAseq_variant_calling/scripts/cons_uniq_morphs.T2T_masked_small_blast_hits/GATK/err/02.02.GATK.pldy_10.JointGenotyping.MQ30.BQ15.MAA20.GC75000.SC10.bqsr.%A_%a.err
#SBATCH --cpus-per-task=16
#SBATCH --qos=debug
#SBATCH --time=00:30:00
#SBATCH --constraint=highmem



# Load required packages
module load java gatk/4.2.6.1 # Nord3: use versions greater than 4.1.6 to solve bug with MNP variants
#module load java/8u201 gatk/4.1.4.1 # mn3
#module load java/8u201 gatk/4.3.0.0 # mn3

# another slurm job : STEP 1 : variant calling indiviually for two libraries cHM13_1_182 and CHM13_2_183
# STEP 2 : Jointgenotyping two output gVCF generated by STEP 1 to get single vcf file
# STEP 3 : convert vcf file to table

# Paths and variables
reference=/gpfs/projects/bsc83/Data/assemblies/T2T/T2T_rDNA/T2T_rDNA.fa

ploidy=$1

dir=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/Aisha/T2T_variant_calling/03_T2T_RNAseq_variant_calling/03.HaplotypeCaller/Consensus_Uniq_Morphs/masked.small_blast_hits.genes.pseudogenes/bqsr.using.benchmark_variants/output_MQ30.BQ15.MAA20.GC75000.SC10.p10
outpath=${dir}/Joint_Genotyping
sample_map=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/Aisha/T2T_variant_calling/03_T2T_RNAseq_variant_calling/scripts/sample_maps_gvcf/Consensus_Uniq_Morphs/masked.small_blast_hits.genes.pseudogenes/bqsr.using.benchmark_variants/ploidy_10.gvcf.MQ30.BQ15.SC10.map
bedfile=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/Aisha/T2T_variant_calling/03_T2T_RNAseq_variant_calling/scripts/T2T_rDNA.Cons_uniq_morphs.bed
database=${outpath}/ploidy_${ploidy}
mkdir -p ${database}



#############################################
#   Joint Genotyping : Consolidating GVCFs  #
#############################################



# Provide sample map with sample IDs and paths to each gvcf to consolidate all samples before performing joint genotyping
gatk --java-options "-Xmx115g -Xms100g"  GenomicsDBImport \
--sample-name-map ${sample_map} \
--genomicsdb-workspace-path ${database}/T2T_database.RNAseq.ploidy_${ploidy} \
--batch-size 50 \
--intervals ${bedfile} \
--genomicsdb-vcf-buffer-size 16384000 \
--reader-threads 2


# Perform joint genotyping using all the samples from the previously created DB
# Check if ploidy equals to 100 (special settings) 
database=${outpath}/ploidy_${ploidy}/T2T_database.RNAseq.ploidy_${ploidy}

gatk --java-options "-Xmx115g -Xms100g" GenotypeGVCFs \
-R ${reference} \
-V gendb://${database} \
-O ${outpath}/T2T_RNAseq.JointGenotyping.ploidy_${ploidy}.output.vcf.gz \
-ploidy ${ploidy} \
--max-alternate-alleles 20 \
--max-genotype-count 75000 



#############################################
##             Variants2table              ##
#############################################
vcf_name=T2T_RNAseq.JointGenotyping.ploidy_${ploidy}.output.vcf.gz

# Extract information from VCF files using GATK. Never parse on your own!!
gatk --java-options "-Xmx115g -Xms100g" VariantsToTable \
-V ${outpath}/${vcf_name} \
-F CHROM -F POS -F TYPE -F AF -F REF -F ALT -F QUAL -F MULTI-ALLELIC -F FILTER -F AC -F AN -F BaseQRankSum -F DP -F FS \
-F MLEAC -F MLEAF -F MQ -F MQRankSum -F QD -F ReadPosRankSum -F SOR -F VAR -GF GT -GF AD -GF DP -GF PL -GF GQ \
-O ${outpath}/T2T_RNAseq.JG.ploidy_${ploidy}.MQ30.BQ15.MAA20.GC75000.SC10.bqsr.table \
--show-filtered true # By default filtered positions are removed. To see them you need this flag
	
	
	
