#!/bin/bash



#SBATCH --job-name="nuccmer and seqkit"
#SBATCH --chdir=/gpfs/projects/bsc83/Projects/ribosomal_RNAs
#SBATCH --output=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/out/nucmer.%A_%a.out
#SBATCH --error=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/error/nucmer.%A_%a.err
#SBATCH --array=1-48 
#SBATCH --cpus-per-task=16
#SBATCH --qos=bsc_ls
#SBATCH --constraint=highmem
#SBATCH --time=02:00:00





: '

IF YOU ALREADY HAVE A FASTA FILE THEN SKIP STEP 0


INPUT : fastq

Step 0    (using seqkit)       : Convert fastq file to fasta (nucmer takes fasta as input) <-- skip this step if you already have fasta file
Step 1.1 (using nucmer)        : Extract candidate reads (having 30nt exact match with reference provided) for both reads of a pair
Step 1.2 (using show-coords)   : Convert delta file generated by step 1.1 to tab-seperated readable coords file 
Step 2.1 (using bash)          : coord file column 13 containg read name , extract all read names for both pairs of a read
Step 2.2 (using seqkit)        : use readIDS from step 2.1 to extract those reads from original fastq files

OUTPUT : fastq with candidate reads


My input was : WGS fastq for 47 samples(one sample missing from 1000 genomes phase 3) from 1000 genomes project

'

##########################################
#  STEP 0 : Convert fastq file to fasta  #
##########################################

# load modules
module load anaconda
conda activate seqkit

# one task for each sample (task id represent sample given in genome_ids.tab file i.e one sample name per line )
export genome_id=$(sed -n "${SLURM_ARRAY_TASK_ID}p" genome_ids.tab | cut -f1)
# path for input fastq files
inpath=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/merged_fastq
# output directory
outpath=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/nucmer/intermediate_files/${genome_id}/fasta_files
mkdir -p ${outpath}

fastq1=${inpath}/${genome_id}_merged_read1.fastq.gz
fastq2=${inpath}/${genome_id}_merged_read2.fastq.gz



echo "*****************************************************************************************************"
echo "Start converting fastq to fasta : $(date)"
echo ""

seqkit fq2fa ${fastq1} > ${outpath}/${genome_id}_1.fasta
seqkit fq2fa ${fastq2} > ${outpath}/${genome_id}_2.fasta

echo "End Start converting fastq to fasta : $(date)"
echo "*****************************************************************************************************"



############################################################
#  STEP 1 : nucmer to extract reads from T2T DNAseq fasta  #
#  files having 30nt exact match with rDNA genes reference #
############################################################


module load mummer

#********#
# INPUT  #
#********#


export sample_id=$(sed -n "${SLURM_ARRAY_TASK_ID}p" genome_ids.tab | cut -f1)                                  # read sample id 
inpath_fasta=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/nucmer/intermediate_files/${sample_id}/fasta_files   # path for fasta file (generated by step 0)
outpath_nucmer=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/nucmer/intermediate_files/${sample_id}             # output directory
mkdir -p ${outpath}

# paths for read1 and 2 of fasta files
READ1=${inpath_fasta}/${sample_id}_1.fasta  
READ2=${inpath_fasta}/${sample_id}_2.fasta

# reference sequence
reference=/gpfs/projects/bsc83/Data/assemblies/T2T/T2T_rDNA/T2T_rDNA.fa


echo "*****************************************************************************************************"
echo "Start extracting fasta readIDs having 30nt exact match with provided reference : $(date)"


#*****************#
# 1.1 RUN Nucmer  #
#*****************#

nucmer --maxmatch -l 30 --delta=${outpath_nucmer}/${sample_id}_1.nucmer.rDNA.delta --threads=16 ${reference} ${READ1}
nucmer --maxmatch -l 30 --delta=${outpath_nucmer}/${sample_id}_2.nucmer.rDNA.delta --threads=16 ${reference} ${READ2}

: '
FLAGS used :
--delta=PATH    Output delta file to PATH (instead of PREFIX.delta)
-l  maximal exact match or anchor match size
--maxmatch	Use all anchor matches regardless of their uniqueness


TO GET SAMFILES
nucmer --maxmatch -l 30 --sam-long=${outpath_nucmer}/${sample_id}_L002_R1_001.nucmer.rDNA.sam --threads=16 ${reference} ${READ1}
nucmer --maxmatch -l 30 --sam-long=${outpath_nucmer}/${sample_id}_L002_R2_001.nucmer.rDNA.sam --threads=16 ${reference} ${READ2}

SAM files have error in headers so it dosent allows snp calling using snp-sites tool from mummer -- I couldnt fix it , I tried solution given here https://github.com/mummer4/mummer/issues/24#issuecomment-884989738 
'

#******************#
# 1.2 show-coords  #
#******************#


# converting delta file to tab seperated coords file
show-coords -r -c -l -T ${outpath_nucmer}/${sample_id}_1.nucmer.rDNA.delta > ${outpath_nucmer}/${sample_id}_1.nucmer.rDNA.coords
show-coords -r -c -l -T ${outpath_nucmer}/${sample_id}_2.nucmer.rDNA.delta > ${outpath_nucmer}/${sample_id}_2.nucmer.rDNA.coords

: '
FLAGS used :
-r      Sort output lines by reference
-c      Include percent coverage columns in the output
-l      Include sequence length columns in the output
-T      Switch output to tab-delimited format
'


# removed unzipped fasta files
#rm READ1 READ2

echo "End extracting fasta readIDss having 30nt exact match with provided reference: $(date)"
echo "*****************************************************************************************************"
echo ""


############################################################
#  STEP 2 : Extracting data from DNA-seq fastq files for   #
#  reads obtained using nuccmer in step 1                  #
############################################################

## Extracting data from DNA-seq fastq files for reads obtained using nuccmer

inpath_DNAseq=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/merged_fastq
outpath_candidate_DNAseq=/gpfs/projects/bsc83/Projects/ribosomal_RNAs/nucmer/candidate_reads_merged_fastq
mkdir -p ${outpath_candidate_DNAseq}

module load anaconda
source activate seqkit


#*****************************#
# 2.1 Extract unique readIDs  #
#*****************************#


echo "**************************************************************"
echo "Start extracting read_IDs : $(date)"
# first five lines are headers of columns in .coord file
# column 13 contains readID so we will get readIDs from both reads of a pair and then combine them to extract all DNAseq pairs having 30nt match in read1 or read2 
tail -n +5 ${outpath_nucmer}/${sample_id}_1.nucmer.rDNA.coords| awk '{print $13}' > ${outpath_nucmer}/readIDs.out
tail -n +5 ${outpath_nucmer}/${sample_id}_2.nucmer.rDNA.coords| awk '{print $13}' >> ${outpath_nucmer}/readIDs.out
# extract unique read ids
cat ${outpath_nucmer}/readIDs.out | sort | uniq > ${outpath_nucmer}/uniq_readIDs.out

echo "End extracting read_IDs  : $(date)"
echo "**************************************************************"
echo ""



#********************************************************************************#
# 2.2 Extract candidte reads from fastq using seqkit and readIDS generated above #
#********************************************************************************#


headers=${outpath_nucmer}/uniq_readIDs.out  # readID headers
READ1_fastq=${inpath_DNAseq}/${sample_id}_merged_read1.fastq.gz     # input original fastq file for read1
READ2_fastq=${inpath_DNAseq}/${sample_id}_merged_read1.fastq.gz     # input original fastq file for read2
READ1_out=${outpath_candidate_DNAseq}/${sample_id}_1_rDNA.fastq     # output candidate fastq reads for read1
READ2_out=${outpath_candidate_DNAseq}/${sample_id}_2_rDNA.fastq     # output candidate fastq reads for read2


echo "**************************************************************"
echo "Start extracting fastq enteries for READ1 using read_ID : $(date)"

seqkit grep -f ${headers} ${READ1_fastq} >> ${READ1_out}

echo "End extracting fastq enteries for READ1 using read_ID   : $(date)"
echo "**************************************************************"
echo ""


echo "**************************************************************"
echo "Start extracting fastq enteries for READ2 using read_ID : $(date)"

seqkit grep -f ${headers} ${READ2_fastq} >> ${READ2_out}

echo "End extracting fastq enteries for READ2 using read_ID   : $(date)"
echo "**************************************************************"
echo ""
















