---
title: "Variant Calling For LCL data"
author: "TFGL-AISHA SHAH"
format: gfm
execute:
  echo: true
  eval: true
  warning: false
  output: true
---

## Downloading Data

### **Information About LCL Data**

**`rRNAseq data generated by`** : [Rodriguez-Algarra et al. 2022](https://doi.org/10.1186/s13059-022-02617-x) study

**`Data download`** [link](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA733656&o=acc_s%3Aa)

**`Population:`** Gambian Mandinka

**`Code:`** GWD

**`Description:`** Gambian in Western Division, The Gambia - Mandinka

**`Superpopulation:`** African Ancestry

**`Superpopulation code:`** AFR

**`Article :`** Genetic variation at mouse and human ribosomal DNA influences associated epigenetic states

**`BioProjectID :`** PRJNA733656

**`Directory name :`** rRNAseq

### Downloading Data

> 1.  **Ribosomal RNAseq data by PRJNA733656**
> 2.  **High-Coverage 1000 WGS data for 1000_Genomes_ID used by PRJNA733656**
>
> ```{bash, eval=FALSE}
> # rRNAseq and corresponding WGS sample names
>
>  awk -F',' '{print $1 "\t" $35}' metadata.txt > rRNA-seq_to_WGS.name_translation.tab 
> ```

**Metadata for PCR-free high covergae WGS data for Mandinka population :** igsr_Gambian_in_Western_Division.The_Gambia_Mandinka_undefined.tsv

Above metadata downloaded from https://www.internationalgenome.org/data-portal/population/GWD

**1000-Genomes-IDs used by PRJNA733656 from above data**

PRJNA733656.1000_Genomes_ID.txt

**list for ftp links for above 1000-Genome IDs**

PRJNA733656.1000_Genomes_ID.ftp_links.txt

> **Script to download fastq files :** download_WGQ_cram_files.sh
>
> **Script to convert cram files to fastq :** cram2fastq.sh

## Scripts For Variant Calling 

Scripts given in directory **`04_T2T-CHM13_Variant_Calling`** were modified to run on 48 LCL samples.
